lua-nginx-module: Autospec creation for update from version 0.10.22 to version 0.10.26
A compound of Fe and O (1):
      bugfix: Fix handling of new list elements.

Blaise Wang (1):
      doc: modify openssl patch requirements. (#2022)

Christian Marangi (1):
      bugfix: don't include pcre.h with PCRE2 used.

Chrono (3):
      doc: modified the todo section. we now have exit_worker_by_lua (#2009)
      bugfix: Apple Silicon FFI ABI limitation workaround
      doc: setoption is already available now.

Datong Sun (1):
      cosocket: add function `tcpsock:setclientcert`, reimplemented `tcpsock:sslhandshake` with FFI

Gordon McKinney (1):
      bugfix: segment fault when get header via ngx.req.raw_header with malformed requests.

Hiroaki Nakamura (1):
      bugfix: update handling of multiple headers changed in nginx 1.23.0 (#2063)

Ilya Shipitsin (3):
      fix potential null pointer dereference found by Coverity (#2043)
      fix dead code found by coverity
      optimize: fix potential null pointer dereference found by coverity (#2051)

James Callahan (1):
      feature: add api to fetch raw nginx ssl pointer of the downstream request.

Jan Prachař (1):
      optimize: Optimized use of SSL contexts.

Johnny Wang (13):
      travis-ci: upgraded openssl to 1.1.1m, pcre to 8.45. (#2002)
      bugfix: fixed size of the array when initialized in the init_worker_by* phase. (#2017)
      tests: 160-disable-init-by-lua.t: prevent the test process from overwriting the original pid file. (#2024)
      tests: use random port numbers instead of fixed port number to prevent conflict. (#2025)
      ci: bumped OpenSSL to 1.1.1p. (#2070)
      tests: use the specified perl to execute cpanm. (#2157)
      Revert "bugfix: doesn't set flags for Darwin arm64. (#2071)" (#2163)
      tests: check if the version number has been specified before downloading OpenSSL. (#2240)
      tests: t/128-duplex-tcp-socket: replacing constant port 7658 with a random port. (#2268)
      tests: t/129-ssl-socket.t: use the same IP to ensure that the ssl session can be reused. (#2267)
      bugfix: fixed memory leak in the case of connection in dubious. (#2270)
      tests: use random ports instead of constant ports to prevent conflicts during testing. (#2274)
      tests: 082-body-filter-2.t: skip this test if mockeagain is not loaded correctly. (#2275)

Jun Ouyang (2):
      doc: complete md5.lua example in run_worker_thread api (#2085)
      bugfix: disable http2 in body read due to http2 stream processing bug.

Landon Manning (1):
      feature: added http const HTTP_NOT_IMPLEMENTED, fixes #1466.

Marcelo Parada (1):
      doc: add link to pre-defined Nginx variables (#2116)

Michael McQuade (1):
      docs: remove duplicated sentence.

Noah Jahn (1):
      doc: fixed link to lua-resty-core

Thibault Charbonnier (1):
      feature: prevent calling ngx.exit() with invalid values.

Tinglong Yang (1):
      change: delete useless code for get old_cpath. (#2000)

Wangchong Zhou (1):
      doc: add detail on explanation of a running timer (#2105)

Xiaobo Liu (4):
      style: removed extra space. (#1981)
      tests: travis.yml: ngx-releng depends on ack. (#1986)
      feature: add four new apis to manipulate the coctx.
      feature: introduced ngx_http_lua_get_lua_http10_buffering.

Yichun Zhang (agentzh) (1):
      doc: mentioned OpenResty.

Yu.Zhu (1):
      feature: added HTTP 3.0 support to ngx.req.http_version().

ZongRun (3):
      bugfix: fix receiveuntil rest bytes count.
      style: use forward declaration.
      bugfix: mixed recv api call causes unexpected result.

attenuation (1):
      feat: add ngx_http_lua_ffi_worker_pids to get all workers pid map

chronolaw (1):
      feature: added ffi-based function 'ngx_http_lua_ffi_req_is_internal'.

detailyang (1):
      tests: removed duplicated c declaration in t/140-ssl-c-api.t.

fesily (1):
      bugfix: run_worker_thread arg is self-reference.

jiahao (2):
      bumped the lua version to 0.10.23.
      bumped the lua version to 0.10.24.

jinhua luo (4):
      bugfix: ngx.run_worker_thread injected api into the wrong table.(#1996)
      feature: add shdict APIs into worker thread (#2074)
      bugfix: avoid buf double free in ngx.print if lua body filter enabled (#2115)
      bugfix: define busy_bufs per cosocket (#2119)

jizhuozhi (1):
      feature: content_by_lua_file return 503 if read err and file is existed #1992 (#1995)

kfang (1):
      doc: Readme: completed the Installation part, with add lua-resty-core and lua-resty-lrucache.

kingluo (1):
      bugfix: did not wakeup coroutine when worker thread finished.

levy001 (1):
      doc: add more explanation for premature in ngx.timer.at.

lijunlong (65):
      doc: Clarify ngx.req.set_header usage for proxies.
      bugfix: posted event handler was called after event memory was freed. (#1982)
      feature: expose the 'Last-Modified' response header as ngx.header["Last-Modified"]. (#1983)
      bugfix: ngx.pipe waits until timeout because child process forgot to close pipe after dup2.
      feature: ssl/tls: support for passphrase protected key. (#1991)
      tests: t/140-ssl-c-api.t failed because got wrong libssl.so.
      bugfix: the error message should use the first line rather than the last line of the code block when load lua code block failed. (#2005)
      optimize: change lua chunkname to config filename and line number for (init/header_filter/body_filter)_by_lua_block and so on. (#2008)
      bugfix: passing the wrong chunkname argument to luaL_loadbuffer. (#2010)
      doc: change description for ssl_client_hello_by_lua.
      bugfix: ambiguous error message 'connection in dubious state' when connection is closed. (#2016)
      tests: change the count of the record after adding ngx.get_raw_phase. (#2019)
      optimize: use ngx_hash_t to optimize the built-in header look-up process for ngx.header.HEADER.
      travis: fixe the uri of lua-resty-core.
      travis: update openssl to 1.1.1n. (#2028)
      doc: did not generate README.markdown from doc/HttpLuaModule.wiki. (#2029)
      bugfix: failed to compile when nginx https is disabled. (#2034)
      bugfix: wrong memory size for the pernding timers array. (#2048)
      optimize: add error log when closing the pipe failed. (#2050)
      bugfix: tctx.pool is double freed. (#2049)
      doc: revised English grammar in ngx_http_lua_timer.c. (#2053)
      optimize: destroy pipe proc when freeing the request. (#2052)
      change: can not receive udp datagram greater 8192. (#2057)
      tests: change the running phase to cover the bug reported in google group. (#2064)
      bugfix: doesn't set flags for Darwin arm64. (#2071)
      doc: clarify the ngx.req.set_uri_args api when using Lua table as the 'arg' argument. (#2073)
      feature: added new API bind.
      tests: build with DDEBUG=1. (#2084)
      doc: add release description for ngx.worker.pids(). (#2104)
      feature: add new ffi api ngx_http_lua_ffi_msec. (#2108)
      bugfix: add a timed recycling child process as a last resort. (#2112)
      tests: upgrade openssl to 1.1.1s. (#2117)
      tests: test failed when running in randmonize mode.
      tests: fixed some test cases in t/129-ssl-socket.t t/162-socket-tls-handshake.t t/186-cosocket-busy-bufs.t.
      bugfix: cosocket did not exit when worker_shutdown_timeout handler is called.
      bugfix: cleanup of http request will not be callled for the request created by ngx_http_lua_create_fake_request.
      tests: cross requests cosocket can only be use one time.
      bugfix: windows does not support ngx_http_lua_ffi_worker_pids.
      bugfix: fixed warning of signed and unsigned.
      bugfix: windows also need to support ngx_http_lua_ffi_worker_pids.
      tests: add two more test cases for body_filter_by_lua*.
      change: lua-ssl-protocols: Disabled SSLv3 and enable TLSv1.3 by default.
      bugfix: used after free when encountering invalid http IF-Match header.
      bugfix: used after free when encountering invalid http IF-Match header.
      bumped version to 0.10.25.
      feature: allow get empty key for ngx.req.get_uri().
      Revert "feature: allow get empty key for ngx.req.get_uri()."
      change: remove ngx.re from ngx.run_worker_thread.
      bugfix: fixed compilation error: variable 'nelts' set but not used.
      doc: revise the description regarding Nginx compatibility.
      tests: update t/cert/test.crl.
      tests: update t/cert/test.crl.
      tests: fixed test for http3.
      test3: more http3 tests fixes.
      tests: fixed test cases for http2 when running with TEST_NGINX_USE_HTTP2=1. (#62)
      enable http3 test.
      bugfix: failed to compile with clang.
      tests: build drizzle with python3.
      tests: t/166-ssl-client-hello.t: fixed test plan.
      bugfix: failed to build when building without http2&http3 modules.
      feature: make HTTP3 authority as http_host header.
      tests: adjust some test cases for HTTP3.
      bumped version of lua-nginx-module to 10026.
      tests: update openssl to 1.1.1w.
      change: don't move the expired item to the lru queue head when lookup.

lynch (1):
      optimize: Make the use of NGX_PCRE2 clearer.

mafh (2):
      bugfix: ssl_client_hello_by_lua generating chunk cache key and chunk name
      bugfix: ssl_client_hello_by_lua generating chunk cache key and chunk name

masterlvng (1):
      feature: add max_bytes argument for get_body_data() function.

menglei (2):
      bugfix: fix some failed test case.
      doc: make some debug message and comments accurate.

oowl (1):
      doc: add http2 and http3 limitation doc comment for ngx.req.socket API.

qyihua (1):
      doc:move all the discouraged *_by_lua documentation to *_by_lua_block

spacewander (2):
      optimize: don't calculate hash when clearing the header.
      optimize: don't calculate hash when clearing the request header.

swananan (3):
      feature: upgrade nginx core to 1.25.1.
      feature: support pcre2
      changes: modify read body api limitation for HTTP/2 or HTTP/3 requests.

tan jinhua (1):
      feature: check the number of parameters for ngx.thread.wait

user.tax (1):
      bugfix : comparison of integer expressions of different signedness.

willmafh (6):
      doc: fixed typo in error messages.
      doc: fix typo in the comment.
      bugfix: when value type is SHDICT_TNUMBER, then it should get the number field instead of the bool field.
      bugfix: ngx_http_lua_socket_tcp_bind is also allowed in ssl_session_fetch_by and ssl_client_hello_by.
      doc: update TODO list since tcpsock:bind is already implemented.
      doc: more accurate error messages.

xiaobiaozhao (2):
      feature: add `server_rewrite_by_lua*`. (#2004)
      ci: add util/build-without-ssl.sh. (#2035)

yang.yang (1):
      change: use nil instead of false when lpush&rpush overflow.

zhangjie (2):
      feature: Support lua_ssl_certificate and lua_ssl_certificate_key.
      doc: modified lua_ssl_certificate, lua_ssl_certificate_key and lua_ssl_trusted_certificate.

罗泽轩 (7):
      feature: add FFI implementation for ngx.arg getter (#2021)
      doc: describe the second argument of get_uri_args (#2023)
      ci: add a way to check PR title automatically (#2067)
      chore: update the PR types (#2069)
      doc: fix the version in README (#2089)
      chore: add assertion to make linter happy (#2107)
      doc: update release date

聪 (1):
      bugfix: typo in the debug message. (#2081)

连志雷 (1):
      doc: fixed typo.